### ISSUE TITLE
Blank screen when choosing Danish

### ISSUE THREAD

**Issue by peterbuitho** [hadrrb/wordle-for-vscode#3]
Switching to the new Danish language displays just a blank screen on VS Code v1.64.0, Windows 10 20H2 (19042.1466).

**Comment by hadrrb** [comment]
Hmm, maybe it has something to do with `ø` character and Windows itself.
Can you try this version? [vscode-wordle-1.0.2.vsix.zip](https://github.com/hadrrb/wordle-for-vscode/files/8027864/vscode-wordle-1.0.2.vsix.zip)
Unpack the zip archive first then install the vsix file using `Install from vsix` command from the command palette.

**Comment by peterbuitho** [comment]
> Hmm, maybe it has something to do with `ø` character and Windows itself. Can you try this version? [vscode-wordle-1.0.2.vsix.zip](https://github.com/hadrrb/wordle-for-vscode/files/8027864/vscode-wordle-1.0.2.vsix.zip) Unpack the zip archive first then install the vsix file using `Install from vsix` command from the command palette.

I've uninstalled version 1.0.1 and installed the new version from the vsix file. The problem gets actually worse, now English, Portuguese and Danish doesn't show.  Other languages work fine.

I've then uninstalled the vsix version and install again Wordle from the market place. English, Portuguese and Danish still does not show!

Does it make any sense?

Thanks a lot, anyway! 👍

**Comment by hadrrb** [comment]
English it's because of NYT acquiring Wordle - I am working on a fix.
For the rest it's weird, especially that I cannot reproduce this behaviour on my Windows machine.

Create an html file containing:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="default-src https:;">
    <title>Wordle</title>

</head>
<body>
    <iframe src="https://www.wørdle.dk" height="100%" width="100%" scrolling="no" frameborder="0" wmode="transparent"></iframe> 
</body>
</html>
```
then just try to open it in your browser. The Danish Wordle should appear, or not.
Basically this is the code launched in VSCode.

**Comment by peterbuitho** [comment]
On the Mac Mini M1 with MacOS 12.1, and VS Code 1.64.2, it works fine for Danish and all other languages, except English of course. 

On the same Mac mini M1 and Safari, the above html only displays correctly with height and width attribute in absolute number. With percentage, it's just cut off!

<img width="1063" alt="Screenshot 2022-02-16 at 21 10 49" src="https://user-images.githubusercontent.com/59470076/154348242-3272a6ae-72de-47a3-abc6-88b147851fc4.png">

Seems like iframe is not working consistently.

**Comment by hadrrb** [comment]
@PeterBuitho Did you try to change the width after the last update? And did it work?

**Comment by peterbuitho** [comment]
It works! Version 1.0.4 seems to solve all the problems I had. Thx!
